baseURL = "https://matheuspaiva.com"
languageCode = "en-us"
title = "Matheus Paiva"
theme = "PaperMod"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-32844244-1"
preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "posts/:slug/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3


[params]
    ShowShareButtons = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    author = "Matheus Paiva"
    description = "Blog sharing thoughts about Software Engineering, Tech Stuff, Self Improvement, and Life."

[params.profileMode]
    enabled = true
    imageUrl = "/images/me/avatar.jpg"
    subtitle = "Software Engineer @ [Google](https://www.linkedin.com/company/google/)"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/mapaiva"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/matheus-paiva-29193879"
[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/mapaiva_a"
[[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/mapaiva_a"
[[params.socialIcons]]
    name = "email"
    url = "mailto:matheus.a.paiva@gmail.com"

[minify]
  minifyOutput = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
