baseURL = "https://matheuspaiva.com"
languageCode = "en-us"
title = "Matheus Paiva (mapaiva)"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-32844244-1"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "posts/:slug/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
    since = 2011
    author = "Matheus Paiva"
    avatar = "/images/me/avatar.jpg"
    subtitle = "Software Engineer | Golang | Elixir | Tech stuff | Life"
    cdn_url = ""			# Base CDN URL
    home_mode = "" 			# post or other

    google_verification = ""
   
    description = "Blog sharing thoughts about Software Engineering, Tech Stuff, Self Improvement, and Life. Mainly about life."
    keywords = "software-engineering, software, technology, blog, golang, elixir, aws, kubenetes, docker, self-improvement, life"

    license= ""

[params.social]
    GitHub = "mapaiva"
    Twitter = "mapaiva_a"
    Email   = "matheus.a.paiva@gmail.com"
    Instagram = "mapaiva_a"
    Telegram = "mapaiva"
    Medium = "@matheus-paiva"
    LinkedIn = "matheus-paiva-29193879"

[minify]
  minifyOutput = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
